### ISSUE TITLE
forge support

### ISSUE THREAD

**Issue by tobyjoiner** [sandain/MinecraftServerControlScript#67]
I am trying to use this script with yogscast complete `forge-1.6.4-9.11.1.965-universal.jar` to be exact.  I keep getting the error `Error starting the server: couldn't retrieve the server's process ID.`

When importing the server and didn't set the `mscs-server-jar` before starting it, so it used the minecraft server jar instead.  Did I mess this up here or is this a different issue?

**Comment by sandain** [comment]
I gave forge a try, and it worked perfectly once I figured out how to install forge.  At least for forge versions that work with 1.8 (I didn't test older versions), I was able to tell the forge installer to place all of the needed files into the `/opt/mscs/server/` directory.  The installer downloaded the forge server to `/opt/mscs/server/forge-1.8-11.14.1.1419-universal.jar` and a bunch of library files and placed them in `/opt/mscs/server/libraries/`.

To get the script to manage the server, I just added the following lines to the `server.properties` file:
```
mscs-client-version=1.8.4
mscs-server-version=1.8.4
mscs-server-jar=forge-1.8-11.14.1.1419-universal.jar
mscs-server-url=http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.8-11.14.1.1419/forge-1.8-11.14.1.1419-universal.jar
```

If you want to try to debug your setup, you can see console output by looking at the `console.out` file in your world's directoyr.

**Comment by tobyjoiner** [comment]
My bad, I didn't even think about installing forge to make sure the right files were in the right places.  Thank you very much for this great script and for the help

**Comment by sandain** [comment]
No worries, it wasn't straight forward to me on my first attempt either.  The main problem that I encountered was the installation of all of the library files, but the forge installer made that part easy once I found out it existed.

If I find the time this next weekend, I'll add a note to either the README or the wiki documenting how to get Forge installed.

**Comment by zanix** [comment]
I added the MSCS set up portion of Forge to the wiki, but not the Forge install itself.

**Comment by sandain** [comment]
Thanks for doing that Zanix.

**Comment by zanix** [comment]
I would have added the forge install instructions as well but I haven't installed forge in a while.

**Comment by sandain** [comment]
I might go ahead and rerun the Forge installation this weekend and update the notes that you placed on the wiki.  I don't remember the process being complex at all, just start the installer and choose the location to place the files.  I think there is even a command line option for the installer that would be handy to document for setting it up over a SSH session.

I'm usually not concerned with old versions, but if I have the time I'll see if older Forge installer versions work the same way.  There are a couple of old forks by Gglachant and Lathanael that added additional Forge support with code to support old versions, but I never accepted the changes because they were overly complex.

**Comment by sandain** [comment]
The wiki has been updated with the Forge install information.  It seemed to work just fine with Forge 1.6.4-9.11.1.1345.
